### ISSUE TITLE
Why use {$$} and {/$$} instead of $$?

### ISSUE THREAD

**Issue by TaurusOlson** [bcaffo/LittleInferenceBook#1]
Hello Brian,

Maybe I'm missing something but the usage of `{$$}` and `{/$$}` around some text makes the latex compiler crash. Why not simply use `$`? (for example `$X$`).

Cheers,
Taurus

**Comment by odeleongt** [comment]
Those markers are used to define $\LaTeX$ [equations in LeanPub](https://leanpub.com/help/manual#leanpub-auto-mathematical-equations), which uses the [markua](http://markua.com/) flavor of markdown (poorly documented).

**Edit:** Prepared a pull request to easily compile the book to html. I doesn't work for pdf yet, but it avoids issues with equation and code block delimiters. bcaffo/LittleInferenceBook#3

**Comment by bcaffo** [comment]
Yup, it's really annoying. Perhaps even annoying is that the convert from md to latex. I should just write in latex, since I know it really well. But leanpub's authoring is really neat
